### ISSUE TITLE
Attachments were not converted

### ISSUE THREAD

**Issue by tetsuya-asai** [qqilihq/partial-emlx-converter#1]
Great! My partial.emlx files were successfully converted to eml files, but all the converted eml files did not contain any attachment file...  although the source emlx files had attachments (cf. attached data source). 
I explored your code, and found "data.body" (after parsing elm) were not an array, but was strings including multi-part border strings, which means the multi-part eml sources  were not parsed correctly. This resulted in appending contents of the original emlx files only, without attaching any file. Do you have any concern on this?

Environment: MacOS X 10.13.4, Node v6.11.0, Apple Mail 11.3
Data source: [data.zip](https://github.com/qqilihq/partial-emlx-converter/files/1949912/data.zip)

Many thanks in advance!

**Comment by qqilihq** [comment]
Thanks for your report, and great that you have provided a test case. I'll have a look at it as soon as I have some spare minutes (tentatively this weekend). I'll get back to you then!

**Comment by qqilihq** [comment]
Here's a quick update, what I've found out so far: 

The issue seems to be, that the `eml-format` lib, which we use in this project, considers email headers case sensitively. In your .emlx file, the header name is `Content-type`, but the `eml-format` lib only handles `Content-Type`.

1. Changing the header manually seems to solve this issue (line 77 in your .emlx file file).

2. This [post](https://stackoverflow.com/questions/6143549/are-email-headers-case-sensitive) suggests, that email headers are to be treated case-insensitively. So the current behavior is too strict.

3. Simplest solution: Ask `eml-format`'s author to make the parsing case-insensitive (would you be willing to open an issue [here](https://github.com/papnkukn/eml-format), @tetsuya-asai?)

4. Other, less favorable workaround in case (3) is not feasible: Write a workaround in this project to take care of above.
